### ISSUE TITLE
Add New Structure Object

### ISSUE THREAD

**Issue by DeraldDudley** [usdot-jpo-ode/wzdx#181]
# New Object: Structure

Adding structures to the specification enables data publishers to inform drivers about structures that affect safe and efficient travel.  Informed drivers and wayfinding applications can reroute drivers to avoid such structures.  Bridges are a good example; They often have height, width, length, weight, or axel restrictions.

Possible Structure Types Include:  Bridge, Overpass, Aqueduct, Tunnel, Cut, Gallery, Retaining Wall, Embankment, Railroad, Building.

## Benefits
- Enables publishes to inform drivers about structures and their restrictions.
- Mitigates loss of life, personal injury, infrastructure damage, lost time and money, unnecessary emissions, and all the other ill effects of incompatible vehicles traversing restricted structures. 
- Fosters in-vehicle warnings about hazards to navigation.
- Extending the specification may draw more agencies into using the Work Zone components of the specification.

## Costs
- Diversifying the specification is off scope.

## Alternative
- Associate a Road Event with a structure type by adding a structure property or a structure subclass.

## Support
- NY State DOT has expressed interest.

## Examples
- [Proposed Model](https://drive.google.com/file/d/1-bE6QxsgndSeO8ZCgM2f8OvPQeSLS1V9/view?usp=sharing)
- [Mapped Structures](https://gist.github.com/DeraldDudley/035204436920760d818c7aa7393f95d4)
- [Mapped Structures with Restriction Notices](https://gist.github.com/DeraldDudley/30927e605bc7938051b10051588bebdc)

**Comment by j-d-b** [comment]
What is the value of adding these structures? It appears to me that all of the benefits listed here will be achieved by adding the `restriction-notice` EventType (#178) and allowing a value and units for road event-level restrictions (#155).

I think there is no end to the list of possible structures that *could* be added, which is problematic. If the purpose is to show an area where there is an effect (restriction) to the roadway, that can be achieved using the updated `restrictions` property on the RoadEvent object and the `restriction-notice` event type.

As discussed in the closed issue #156, the consensus of WZDx members seems to be that WZDx should not be used to represent the base details of a roadway (i.e. asset layer), just notable effects to travelers due to road work or a restriction due to a structure. I see minimal value in knowing that a restriction is due to a particular structure type, just that there is a restriction. If the structure does not lead to a restriction, then there is no point in representing it. 

Let me know if I am missing potential use cases. The benefits listed above are just not substantial enough to convince me of the value.

I would also like to hear from any prospective consumers regarding why they would want structure information and how it would be used.

**Comment by DeraldDudley** [comment]
## Maximizing Benefits
The Work Zone Data Specification is an amazing piece of collaborative work.  There is no doubt in my mind its implementation will save lives.  However, we squander the specification’s potential impact by restricting its use to describing only work zones.  Restricting its use reduces the specification’s social benefit by making only a portion of the population safer.  To maximize the specification’s social benefit we need to extend it, in a controlled manner, to enhance the safety of the most people possible.

I agree scope creep is an issue.  We deflect resources away from the work zone data specification by developing non-work zone features.  To overcome this issue the WZDx Working Group established the Extension Subgroup.  It investigates potential features without syphoning Work Zone Data Specification resources.  I argue the extension subgroup, and its exploration of different uses, strengthens the specification by making it more useful which fosters participation and implementation.

## Don’t Comingle Object Types 
Good data modeling practices dictate we not comingle objects and properties.

## Costs 
Not sure what this adds up to, let’s say $20,000.00
- 5 hours identifying candidate features
- 5 hours prioritizing features
- 5 hours modeling 
- 100 hours socializing the idea via meetings and discussions
- IT Costs (Software, Hardware)
- Fork, Develop, Pull Request, Adopt

## Benefits
The purpose of geospatial data is to inform decisions.  Including structures in the specification will foster better decisions and facilitate safe travel.  If we can save one life, prevent a single injury, or avoid damaging a single bridge the effort will probably net a social benefit.

I can’t think of every use case in which mapped structures might inform decisions; there are too many.  Here are a couple:
- Structures fulfill the same purpose as the beginning_cross_street and ending_cross_street propertiesin the Road Event object – informed spatial awareness fosters better decisions.
- Routing oversized loads around restrictive bridges 
- (After writing this, there is probably a case for spatially enabling the cross streets.)

## Consumer Interests
The 4 co-chairs of the extension subgroup, representing Google, Here, the National States Geographic Information Council, the New York State Department of Transportation, The US Department of Transportation and the Federal Geographic Data Committee, spent a few hours identifying candidate features for inclusion in the specification.  All agreed low clearances were the top priority.  Three of the four initially identified bridges as a priority.  All agreed bridges were a priority after discussing the candidate list.  I would like to hear from more prospective consumers too.

## Implementation
This is an optional element.  The burden of including it as a test feature in the specification is minimal.  If it’s useful, demand for it will grow and we can keep it.  If it’s not useful, demand for it will wither and we can toss it.  Either way, we should have room to test new features.

**Comment by frankwintersnsgic** [comment]
I like the structures concept.  While it is true that restrictions could be conveyed as restrictions, the people who will provide this data think in terms of structures.  When we workshopped this with NSGIC we started with clearance as a priority.  the group was quick to add posted load and width restrictions on structures.  The structures will also be a useful for wayfinding providers to communicate to drivers.  'this restriction is on the Western Gateway Bridge'.

**Comment by seyoung1991** [comment]
I have been hearing a lot of aspirational expectations of WZDX – more or less growing into the conduit to communicate any critical information to either travel websites of mapping companies.  I am both encouraged and hesitant with these aspirations.   

That is where my thoughts on this structures suggestion for an object.   I am both encouraged, but hesitant, be it weight limits or height restrictions --- this information is definitely needed, but at the same time I question of whether WZDX is the location or appropriate conduit.  I have been rather silent on the calls – half because I am treading water coming up to speed, but also due to these larger issues of scope.

I have heard (in other venues) the hope to grow the WZDX into a conduit to communicate fundamental network changes (new interchange, bypass, state route) to mapping companies.  Again – yes it is needed, but the scope on WZDX is turning into ‘everything we need to communicate outwardly’.  Should we instead stub these out and get going on the next standard digital interface(?)

Perhaps we need to simply to fork the effort – keep WZDX thematically pure to works zones, and simultaneously create the bridge and structures data feed (BSDX) – for height, weight, length restrictions targeted for specific group of vehicles, typically large vehicle or commercial vehicles.  Similarly, with fundamental network changes (new roads, bypasses, etc.) get involved / start an effort in the mapping space to set up standard conduits for these changes.  The TETC is getting the participants at the table now in this arena.  

I feel there is a ton of work to be accomplished in this digital interface space between DOTs and industry, and if we try to squeeze into this one pipe (WZDX) it may burst.

**Comment by DeraldDudley** [comment]
I love this discussion!

**Comment by j-d-b** [comment]
> Perhaps we need to simply to fork the effort – keep WZDX thematically pure to works zones, and simultaneously create the bridge and structures data feed (BSDX) – for height, weight, length restrictions targeted for specific group of vehicles, typically large vehicle or commercial vehicles. Similarly, with fundamental network changes (new roads, bypasses, etc.) get involved / start an effort in the mapping space to set up standard conduits for these changes. The TETC is getting the participants at the table now in this arena.

@seyoung1991 I agree about the structures being a separate feed (if there is continued demand to address them), not part of the WZDx feed.

See #191 for another example of a new feed and things to think about when implementing a structures feed and how it fits in and is presented alongside WZDx.

**Comment by sknick-iastate** [comment]
Closing for a lack of interest at this point.
