### ISSUE TITLE
Marked Location Object with road_event_id

### ISSUE THREAD

**Issue by sknick-iastate** [usdot-jpo-ode/wzdx#224]
Issue name: “Marked Location Object with road_event_id”
 ## Summary
Currently in the smart work zone device feed (SwzDevice) the [MarkedLocations Object](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/MarkedLocation.md) has an optional field to provide the `road_event_id`.  In addition to that the `FieldDeviceCoreDetails` already includes the ability to also provide an array of `road_event_ids`.  This seems redundant since the information could be located in two different locations for these types of devices which are both optional.

Because the `marked_locations` allows for an array, I assume the use case for this is that a marked location (which can only represent a single point) is being used across two road events (i.e the begin location for one road event and the end location of another road event).  So a scenario like this could play out:

- 'FieldDeviceCoreDetails' contains an array of two road events of `Road Event A` and `Road Event B`
- The first object in the `marked_locations` array is for the begin point of `Road Event A`
- The second object (which represents the same point) in the `marked_locations` array is for the end point of `Road Event B`

A similar situation also occurs with the [traffic sensors](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/objects/TrafficSensor.md) where the individual lanes can be associated with `road_event_id`

 ## Proposed changes
Discussion on whether this is the desired implementation of whether other methods could be identified.  One possibility is to not include `road_event_ids` in the core details but require it for each device object based on how the device is used within the work zone.

**Comment by Dunge** [comment]
I agree it's a bit confusing. The term `MarkedLocation` also bring confusion because they aren't different locations. The coordinates are at the `LocationMarker` level. Each `MarkedLocation` in the same `LocationMarker` represent the exact same position, but is used to represent which type of element it is and on which `RoadEvent` they are linked to. Every `LocationMarker` can indeed be part of multiple `RoadEvent`. Either on an event split (end/beginning) as mentioned, or just for bidirectional roads (one event per direction).

I understand the concept of having a `LocationMarker` with two ids in the `road_event_ids` list in `FieldDeviceCoreDetails`, and two `MarkedLocation`, one for example being a `road-event-end` with one `road_event_id` and another being a `road-event-start` with another `road_event_id`. But if you ask me, for this situation I would prefer having a single `road-event-split` type and just the id list in the core details, not having to specify which one with multiple `MarkedLocation`. Every other types (lane closure, traffic light, etc.) can also be part of one or many `RoadEvent`, but simply having them listed in the core details `road_event_ids` list would be sufficient, I don't think having to duplicate them in a list pointing to each event individually bring any additional information.

So my proposition would be to completely drop the `MarkedLocation` object and just have a list of `MarkedLocationType` in the `LocationMarker` object instead, and keep using the `road_event_ids` in the core details as with every other devices. It would be simpler to produce and understand for consumers without really losing anything. But I'm probably missing some reasoning for this choice and curious to hear about Jacob intentions with this design.

As for the traffic sensors lane, I asked a similar question in #195 yesterday and the justification is to have a link to the lane definitions since they aren't part of the SwzDeviceFeed, and it make sense to have some kind of precision which lane represent which element in the other feed, which isn't possible with just the list in core details. But I would still vote to make it optional. I also have a few design question related to traffic sensor, especially those reporting both directions, the current object is not perfect to present that information, but this would be better placed in another issue.

**Comment by sknick-iastate** [comment]
Closing this issue.  This was discussed at a previous SWZ Device sub group meeting.  Including the road event in the marked location allows for defining the marked location type (which may be on multiple road events) which isn't feasible by using the road event in the core details without replicating the device multiple times.
