### ISSUE TITLE
Rename ‘center-left-turn-lane’ LaneType to ‘two-way-center-turn-lane’ to support countries that drive on the right side of the road

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/wzdx#234]
## Background

At this time, WZDx is primarily used in North America, however, it seeks to be usable worldwide and has used global standards (such as kilometers per hour, see #174) in recent changes.

There are still properties or enumerated type values in WZDx that apply only to certain countries—one of these is the [LaneType](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/enumerated-types/LaneType.md) value of `center-left-turn-lane`, which is used to describe a lane in the center of a bidirectional roadway that supports two way traffic for turning left from either direction of travel. 

## Proposal

By renaming the `center-left-turn-lane` property to `two-way-center-turn-lane` and clarifying it's usage in the description (i.e. equivlant to "two way left turn lane" (TWLTL) for right side driving countries), we would expand the ability for this property to be used for countries that drive on the left side of the road.

**Comment by sergebeaudry** [comment]
I do not have objection. Do we have people from outside North America in the exchanges.  To see if their countries have willingness to use a standard like WZDx.   
That may open others discussions as the naming convention between countries are not always the same ex in UK a road project is a road scheme.  Carriageway versus lanes. etc...

**Comment by eli104** [comment]
I find no problem with making the term more "generic." So yes, removing the term "Left" is probably a reasonable idea as it makes the term more "universal." 

On @sergebeaudry 's second comment, I do NOT believe that, in general, the specific terms should be a concern across other countries any more than it might be an issue in the US (and North America). There are dozens (or more) naming differences across the US for late types, depending on the state and local terminology. A Breakdown lane in one area is a Berm in another; an Express Lane in one area may be a Car Lane in another, etc. I learned ages ago that common names for roads and lanes were far more important to the end users than what was defined is listed on any map. But in order to work across borders, you must make available and neutral and understandable format that can be understood across these "common name" situations, 

Based on map data in the UK, the term "Exit" is not always used for highway  (actually, Motorway) junctions. 
Example: Some junctions on the A1 Motorway are named "Exit", while others are "Interchange", and sometimes the complex junction (which includes road segments) includes both names within the group. The individual lane names/terms will likely vary in the same way, just as they do in the US.

Therefore, I believe that WZDx will work best if the terms we use are understandable and universal (or perhaps, neutral), so even if the local terms commonly used may differ, the agency (users) will understand the purpose... which will liekly come out as coding on the other end anyway. The "coding" of the lanes and detail available will be determined by which map data products are used, and by the Location Referencing format (i.e. TMC vs. Lat/Lon, and others) that works for the agency. The codes will then reference from or to whatever names the agency has available in their own common use.

**Comment by j-d-b** [comment]
Resolved in #314.
