### ISSUE TITLE
Add a new device type for a work truck with its hazard lights flashing

### ISSUE THREAD

**Issue by rdsheckler** [usdot-jpo-ode/wzdx#298]
Beyond the interstate highway system the most common warning or traffic control device on the roadways is the flashing hazard lights on a work truck.  A utility truck on a secondary road is an example.  Can we either add a device type or make this part of a 'marked-location' or 'flashing-beacon'?

**Comment by RHolt-RIDOT** [comment]
Good question.  I'm not sure of best answer/way forward, but it is true that for some work zones (usually mobile and/or short-duration, per MUTCD's definitions) the work vehicle with its high-intensity rotating, flashing, oscillating, or strobe lights on a maintenance vehicle may be 'all that is provided' for TTC, other than workers wearing their Hi-Vis PPE if outside of the vehicle.  

I do not know if the wzdx specs to date have already considered this or not, but if they haven't (or if this input is new and helpful), from all stakeholder perspectives I can see how the tracking and dissemination of the location of such work vehicles could potentially provide value.   For DOTs, improved situational awareness and perhaps management of work zones; For industry, I assume the same, plus business purposes might be ancillary value; and For the (most important of all) road users, I assume safety messages could be applicable at least in certain cases.

Another note I add at this point is the following:   Section 6F.81 Lighting Devices of the current MUTCD includes the following (provided here for easy reference):

  Option:
  03 Lighting devices may be used to supplement retroreflectorized signs, barriers, and channelizing devices.
  04 During normal daytime maintenance operations, the functions of flashing warning beacons may be provided by high-intensity rotating, flashing, oscillating, or strobe lights on a maintenance vehicle.
**Standard:
  05 Although vehicle hazard warning lights are permitted to be used to supplement high-intensity rotating, flashing, oscillating, or strobe lights, they shall not be used instead of high-intensity rotating, flashing, oscillating, or strobe lights.**

In line with Standard 05 above, TMK many if not most (all?) DOTs will not allow only vehicle hazard warning lights to be activated if actively used as part of the 2 types of work zones I note at the top - typically the extraneous high-intensity rotating, flashing, oscillating, and/or strobe lights are required to be activated.

**Comment by rdsheckler** [comment]
So, from the equipment point of view we look at it as monitoring the actions of the piece of equipment.  In this case we figure that if the operator turned on the flashers it was because he needed the drivers to know he was there.  So, we tie into that switch and just report that the operator has activated what ever flashing light system is installed.

**Comment by RHolt-RIDOT** [comment]
> So, from the equipment point of view we look at it as monitoring the actions of the piece of equipment. In this case we figure that if the operator turned on the flashers it was because he needed the drivers to know he was there. So, we tie into that switch and just report that the operator has activated what ever flashing light system is installed.

Thanks, I can understand this.  In this case (like any/most cases?), the flashing lights are activated to call attention to (provide a Warning to road users of) the slow moving or stopped work vehicle, and the risks that are associated with such (may include workers on foot outside the vehicle, a mobile but in- or by-vehicle inspection, or something else).    As noted earlier, I can see cases where tracking/reporting/disseminating data RE: such work vehicles w/ emergency lights activated could be helpful (provide value) to all types of stakeholders.

**Comment by j-d-b** [comment]
Implemented in v4.2.
